-- Current sql file was generated after introspecting the database
-- If you want to run this migration please uncomment this code before executing migrations
/*
CREATE SEQUENCE "public"."users_seq" INCREMENT BY 50 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1;--> statement-breakpoint
CREATE TABLE "users" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "users_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"email" varchar(255) NOT NULL,
	"name" varchar(255) NOT NULL
);
--> statement-breakpoint
CREATE TABLE "shopping_list_item" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "shopping_list_item_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"checked" boolean NOT NULL,
	"name" varchar(255) NOT NULL,
	"quantity" real NOT NULL,
	"unit" varchar(255) NOT NULL,
	"week_plan_id" bigint NOT NULL,
	CONSTRAINT "uk_shopping_list_week_name_unit" UNIQUE("name","unit","week_plan_id")
);
--> statement-breakpoint
CREATE TABLE "recipes" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "recipes_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"title" varchar(255) NOT NULL,
	"url" varchar(255) NOT NULL,
	"ingredients_raw" text
);
--> statement-breakpoint
CREATE TABLE "week_plan" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "week_plan_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"status" varchar(255),
	"week_start_date" date NOT NULL,
	"user_id" bigint NOT NULL,
	CONSTRAINT "uk_week_plan_user_week_start" UNIQUE("week_start_date","user_id")
);
--> statement-breakpoint
CREATE TABLE "day_plan" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "day_plan_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"planned_date" date NOT NULL,
	"recipe_id" bigint,
	"week_plan_id" bigint NOT NULL,
	CONSTRAINT "uk_day_plan_week_plan_date" UNIQUE("planned_date","week_plan_id")
);
--> statement-breakpoint
CREATE TABLE "ingredient" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "ingredient_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"name" varchar(255) NOT NULL,
	"quantity" real,
	"unit" varchar(255) NOT NULL,
	"recipe_id" bigint NOT NULL,
	"raw_text" text
);
--> statement-breakpoint
ALTER TABLE "shopping_list_item" ADD CONSTRAINT "fkh1g3km8b60e05hnfbkwlequ72" FOREIGN KEY ("week_plan_id") REFERENCES "public"."week_plan"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "week_plan" ADD CONSTRAINT "fk1rg7wnw31v9uq8x5jsu78ns6e" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "day_plan" ADD CONSTRAINT "fk4ukvjvqkenqf92tlvj5gdmlol" FOREIGN KEY ("recipe_id") REFERENCES "public"."recipes"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "day_plan" ADD CONSTRAINT "fkk3qwg90npoo0btw5hfh2d5ytu" FOREIGN KEY ("week_plan_id") REFERENCES "public"."week_plan"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "ingredient" ADD CONSTRAINT "fk88h2tluyw2likhrjlciynjg90" FOREIGN KEY ("recipe_id") REFERENCES "public"."recipes"("id") ON DELETE no action ON UPDATE no action;
*/